arrowParens: always
jsxBracketSameLine: true
singleQuote: true
trailingComma: es5
importOrder:
  - "^@app/(.*)$"
  - "^@containers/(.*)$"
  - "^@modules/(.*)$"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
